<a href="https://colab.research.google.com/github/PNU-Mar7th/AiPython/blob/main/250509.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])       # 첫 번째 요소
print(arr[-1])      # 마지막 요소
print(arr[1:4])     # 1~3번 인덱스 값

10
50
[20 30 40]


In [ ]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

print(matrix[0, 1])      # 첫 번째 행, 두 번째 열
print(matrix[1:])        # 두 번째 행 이후 모두

2
[[3 4]
 [5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Min/Max:", np.min(arr), np.max(arr))

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Min/Max: 1 5


In [7]:
import numpy as np
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [9]:
b = np.arange(2,11,2)
print(b)

[ 2  4  6  8 10]


In [10]:
c = np.array([2, 4, 6])
d = np.array([10, 20, 30])
print(c * d)

[ 20  80 180]


In [12]:
c = np.array([2, 4, 6])
d = np.array([10, 20, 30])
e = c * d
print(e[e > 20])

[ 80 180]


In [13]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64


In [14]:
data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}

df = pd.DataFrame(data)
print(df)

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [16]:
df.to_csv('output_students.csv', index=False)

In [19]:
df = pd.read_csv('output_students.csv')
print(df.head())  # 처음 5행만 출력
print(df.info())

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      3 non-null      object
 1   나이      3 non-null      int64 
 2   성별      3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None
